### ISSUE TITLE
Calligraphy crashes on Android P when trying expand WebView Popup list.

### ISSUE THREAD

**Issue by tpiDev** [InflationX/Calligraphy#30]
Calligraphy crashes on Android P when trying expand WebView PopUp list. It seems to be Samsung specific crash. Reproduction is 100%. It does not reproduce with Pixel (Android 9)
With removed Calligraphy from project, WebView displays properly.

**Affected device:** Samsung Galaxy Tab A 10.1 2019 32GB LTE SM-T515 (SM-T515NZKDXEO)
**OS**: Android 9
**com.android.chrome**: 74.0.3729.157 (code 372915702)

**minSdkVersion**: 19
**targetSdkVersion**: 28
**io.github.inflationx:calligraphy**: 3:3.1
**io.github.inflationx:viewpump**: 2.0.2

**StackTrace**:
```
2019-05-17 11:53:29.836 W/System.err: android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class TextView
2019-05-17 11:53:29.836 W/System.err: Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class TextView
2019-05-17 11:53:29.841 W/System.err: Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x20b017c
2019-05-17 11:53:29.841 W/System.err:     at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:291)
2019-05-17 11:53:29.841 W/System.err:     at android.content.res.Resources.getResourceEntryName(Resources.java:2017)
2019-05-17 11:53:29.841 W/System.err:     at io.github.inflationx.calligraphy3.Calligraphy.matchesResourceIdName(Calligraphy.java:94)
2019-05-17 11:53:29.841 W/System.err:     at io.github.inflationx.calligraphy3.Calligraphy.isActionBarTitle(Calligraphy.java:57)
2019-05-17 11:53:29.841 W/System.err:     at io.github.inflationx.calligraphy3.Calligraphy.getStyleForTextView(Calligraphy.java:33)
2019-05-17 11:53:29.841 W/System.err:     at io.github.inflationx.calligraphy3.Calligraphy.onViewCreatedInternal(Calligraphy.java:139)
2019-05-17 11:53:29.841 W/System.err:     at io.github.inflationx.calligraphy3.Calligraphy.onViewCreated(Calligraphy.java:117)
2019-05-17 11:53:29.841 W/System.err:     at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:19)
2019-05-17 11:53:29.841 W/System.err:     at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
2019-05-17 11:53:29.841 W/System.err:     at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
2019-05-17 11:53:29.841 W/System.err:     at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2.onCreateView(-ViewPumpLayoutInflater.kt:350)
2019-05-17 11:53:29.841 W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
2019-05-17 11:53:29.842 W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
2019-05-17 11:53:29.842 W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
2019-05-17 11:53:29.842 W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
2019-05-17 11:53:29.842 W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
2019-05-17 11:53:29.842 W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
2019-05-17 11:53:29.842 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
2019-05-17 11:53:29.842 W/System.err:     at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:53)
2019-05-17 11:53:29.842 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
2019-05-17 11:53:29.842 W/System.err:     at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:44)
2019-05-17 11:53:29.842 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
2019-05-17 11:53:29.842 W/System.err:     at cJL.getView(PG:19)
2019-05-17 11:53:29.842 W/System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:3219)
2019-05-17 11:53:29.842 W/System.err:     at android.widget.ListView.onMeasure(ListView.java:1326)
2019-05-17 11:53:29.842 W/System.err:     at android.view.View.measure(View.java:24954)
2019-05-17 11:53:29.842 W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
2019-05-17 11:53:29.842 W/System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
2019-05-17 11:53:29.842 W/System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
2019-05-17 11:53:29.842 W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
2019-05-17 11:53:29.842 W/System.err:     at android.view.View.measure(View.java:24954)
2019-05-17 11:53:29.842 W/System.err:     at cMB.d(PG:53)
2019-05-17 11:53:29.843 W/System.err:     at cJO.a(PG:8)
2019-05-17 11:53:29.843 W/System.err:     at cwX.<init>(PG:11)
2019-05-17 11:53:29.843 W/System.err:     at org.chromium.content.browser.input.SelectPopup.show(PG:40)
2019-05-17 11:53:29.843 W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-05-17 11:53:29.843 W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:326)
2019-05-17 11:53:29.843 W/System.err:     at android.os.Looper.loop(Looper.java:181)
2019-05-17 11:53:29.843 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7072)
2019-05-17 11:53:29.843 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-05-17 11:53:29.843 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-05-17 11:53:29.843 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2019-05-17 11:53:29.847 E/WifiConnectivityMonitor: msg.arg1 != mRssiFetchToken
2019-05-17 11:53:29.854 A/chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
2019-05-17 11:53:29.856 A/libc: Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0xe6735000 in tid 10822 (roid.production), pid 10822 (roid.production)
2019-05-17 11:53:29.938 I/crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
2019-05-17 11:53:29.942 I//system/bin/tombstoned: received crash request for pid 10822
2019-05-17 11:53:29.944 I/crash_dump32: performing dump of process 10822 (target tid = 10822)
2019-05-17 11:53:29.965 A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-05-17 11:53:29.965 A/DEBUG: Build fingerprint: 'samsung/gta3xleea/gta3xl:9/PPR1.180610.011/T515XXU1ASCK:user/release-keys'
2019-05-17 11:53:29.965 A/DEBUG: Revision: '4'
2019-05-17 11:53:29.965 A/DEBUG: ABI: 'arm'
2019-05-17 11:53:29.965 A/DEBUG: signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0xe6735000
2019-05-17 11:53:29.965 A/DEBUG: Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
    '
2019-05-17 11:53:29.965 A/DEBUG:     r0  00000000  r1  c88e12a0  r2  00000400  r3  00000000
2019-05-17 11:53:29.965 A/DEBUG:     r4  ffdc3108  r5  d0ee14d8  r6  e70683c8  r7  ffdc30ec
2019-05-17 11:53:29.965 A/DEBUG:     r8  e706dd94  r9  ffdc3544  r10 ffdc3540  r11 ffdc353c
2019-05-17 11:53:29.965 A/DEBUG:     ip  ffdc310c  sp  ffdc30d8  lr  cf8f32d1  pc  cf8f33ba
2019-05-17 11:53:30.054 A/DEBUG: backtrace:
2019-05-17 11:53:30.054 A/DEBUG:     #00 pc 023003ba  /data/app/com.android.chrome-1HS2RCE7TlSpdPbYl-VZLg==/base.apk (offset 0x1ee5000)
```

**Comment by tpiDev** [comment]
See pull request solving issue: https://github.com/InflationX/Calligraphy/pull/31/commits

**Comment by tpiDev** [comment]
Any update? It's critical issue.

**Comment by zhuangzhitu** [comment]
what is  PopUp list?

**Comment by chrisjenx** [comment]
Have you tried using ViewPump 2.0.3? See: https://github.com/InflationX/Calligraphy/issues/35#issuecomment-676523448

**Comment by tpiDev** [comment]
@chrisjenx yes, project is using ViewPump 2.0.3 and it did not help. 
This change: https://github.com/tpiDev/Calligraphy/commit/a2e6ee32ec0cfdbdff03d242d7b53d4a7efac5b5 solved issue long time ago (2019-2020-2021 ;) ):, unfortunately never merged.
