### ISSUE TITLE
ViewPump shows deprecation error.

### ISSUE THREAD

**Issue by tateisu** [InflationX/Calligraphy#61]
ViewPump new version shows deprecation error that suggests don't use global ViewPump instance.

**Comment by mrfaa** [comment]
Also here:

    implementation 'io.github.inflationx:calligraphy3:3.1.1'
    implementation 'io.github.inflationx:viewpump:2.1.1'

![grafik](https://github.com/InflationX/Calligraphy/assets/3984124/206263d8-1efc-44e6-b4b8-2b978b56c8ac)

**Comment by tateisu** [comment]
```
 Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x1c
                                         	at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:305)
                                         	at android.content.res.Resources.getResourceEntryName(Resources.java:2412)
                                         	at io.github.inflationx.calligraphy3.Calligraphy.matchesResourceIdName(Calligraphy.java:94)
```

also, maybe Calligraphy does not recognize resource ids in app package. 

https://developer.android.com/build/releases/gradle-plugin
> android.nonTransitiveRClass
> AGP 8.0 generates R classes for resources defined in  the current module only.

**Comment by roumenh** [comment]
Maybe its already time to migrate to native solution instead of using 4 years old ancient library :) 
https://davidmigloz.medium.com/migrating-custom-fonts-from-calligraphy-to-android-fonts-3b635fd945dc

**Comment by sepehrppp** [comment]
guys is there any way to fix ViewPump.init command in new Android Studio?
it says that is deprecated and didn't know this command anymore.
